# Generated by Django 5.2.18 on 2026-10-08 02:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="nombre"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "género",
                "verbose_name_plural": "géneros",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                ("biography", models.TextField(blank=True, verbose_name="biografía")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="people/", verbose_name="foto"
                    ),
                ),
            ],
            options={
                "verbose_name": "persona",
                "verbose_name_plural": "personas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1888),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="año",
                    ),
                ),
                ("synopsis", models.TextField(blank=True, verbose_name="sinopsis")),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="duración (min)"
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True, upload_to="posters/", verbose_name="póster"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="última modificación"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        related_name="movies", to="movies.genre", verbose_name="géneros"
                    ),
                ),
                (
                    "cast",
                    models.ManyToManyField(
                        blank=True,
                        related_name="acted_movies",
                        to="movies.person",
                        verbose_name="reparto",
                    ),
                ),
                (
                    "director",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="directed_movies",
                        to="movies.person",
                        verbose_name="director",
                    ),
                ),
            ],
            options={
                "verbose_name": "película",
                "verbose_name_plural": "películas",
                "ordering": ["-year", "title"],
            },
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer", models.CharField(max_length=100, verbose_name="autor")),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        help_text="De 1 a 5 estrellas.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="puntuación",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comentario")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="movies.movie",
                        verbose_name="película",
                    ),
                ),
            ],
            options={
                "verbose_name": "valoración",
                "verbose_name_plural": "valoraciones",
                "ordering": ["-created_at"],
            },
        ),
    ]
